no_of_sensors = 1
max_bandwidth = 200
median_computation_delay = 0.048
no_of_episodes = 10000     
len_of_episode = 50
max_load = 10 # make it 20
beta = 4
alpha = 0.005
# learning_rate =  0.0001
learning_rate =  1e-07
discount_rate = 0.95
gamma_decay = 1.8e-06
batch_size = 128
nS = 1*beta + 1
nA = 2**beta - 1
exploit_or_explore = []
epsilon_curve=[]
episode_access_rate = []
avg_waiting_time = []
latencies = []
deviations = []
rewards = []
action = []
load_arr = []